title: Mimicking Vocal Tracks by Implementing and Applying Vocoder Effect
description: Junwon Lee, Yoonjin Chung
show_downloads: false
darkmode: false
remote_theme: tuur29/pages-themes-cayman
color:
  gradient_left: "#135FD2"
  gradient_right: "#5FAAFA"
  header: "#fff"
  android_theme: "#fff" # this default to gradient_color
  link: "#5FAAFA" # this default to gradient_color
  section_title: "#135FD2" # this default to gradient_color
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css
buttons:
  zip_url: https://github.com/YoonjinXD/vocoder_project
  zip_title: Project Repository
  zip_hide: false
  tar_hide: true
  github_hide: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-tabs
  - github-pages